// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package sparklepony

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_65d814d4061fbffb, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Price                string   `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	StoreName            string   `protobuf:"bytes,6,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	StoreAvatarUrl       string   `protobuf:"bytes,7,opt,name=store_avatar_url,json=storeAvatarUrl,proto3" json:"store_avatar_url,omitempty"`
	StoreDescription     string   `protobuf:"bytes,8,opt,name=store_description,json=storeDescription,proto3" json:"store_description,omitempty"`
	Featured             bool     `protobuf:"varint,9,opt,name=featured,proto3" json:"featured,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_65d814d4061fbffb, []int{1}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Item) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Item) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *Item) GetStoreAvatarUrl() string {
	if m != nil {
		return m.StoreAvatarUrl
	}
	return ""
}

func (m *Item) GetStoreDescription() string {
	if m != nil {
		return m.StoreDescription
	}
	return ""
}

func (m *Item) GetFeatured() bool {
	if m != nil {
		return m.Featured
	}
	return false
}

type FeaturedItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Quote                string   `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	StoreName            string   `protobuf:"bytes,5,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	StoreAvatarUrl       string   `protobuf:"bytes,6,opt,name=store_avatar_url,json=storeAvatarUrl,proto3" json:"store_avatar_url,omitempty"`
	Price                string   `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Category             string   `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeaturedItem) Reset()         { *m = FeaturedItem{} }
func (m *FeaturedItem) String() string { return proto.CompactTextString(m) }
func (*FeaturedItem) ProtoMessage()    {}
func (*FeaturedItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_65d814d4061fbffb, []int{2}
}
func (m *FeaturedItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeaturedItem.Unmarshal(m, b)
}
func (m *FeaturedItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeaturedItem.Marshal(b, m, deterministic)
}
func (dst *FeaturedItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeaturedItem.Merge(dst, src)
}
func (m *FeaturedItem) XXX_Size() int {
	return xxx_messageInfo_FeaturedItem.Size(m)
}
func (m *FeaturedItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FeaturedItem.DiscardUnknown(m)
}

var xxx_messageInfo_FeaturedItem proto.InternalMessageInfo

func (m *FeaturedItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FeaturedItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *FeaturedItem) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *FeaturedItem) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *FeaturedItem) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *FeaturedItem) GetStoreAvatarUrl() string {
	if m != nil {
		return m.StoreAvatarUrl
	}
	return ""
}

func (m *FeaturedItem) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *FeaturedItem) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type ItemsReply struct {
	Item                 []*Item  `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsReply) Reset()         { *m = ItemsReply{} }
func (m *ItemsReply) String() string { return proto.CompactTextString(m) }
func (*ItemsReply) ProtoMessage()    {}
func (*ItemsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_65d814d4061fbffb, []int{3}
}
func (m *ItemsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsReply.Unmarshal(m, b)
}
func (m *ItemsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsReply.Marshal(b, m, deterministic)
}
func (dst *ItemsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsReply.Merge(dst, src)
}
func (m *ItemsReply) XXX_Size() int {
	return xxx_messageInfo_ItemsReply.Size(m)
}
func (m *ItemsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsReply proto.InternalMessageInfo

func (m *ItemsReply) GetItem() []*Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type FeaturedItemsReply struct {
	Item                 []*FeaturedItem `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FeaturedItemsReply) Reset()         { *m = FeaturedItemsReply{} }
func (m *FeaturedItemsReply) String() string { return proto.CompactTextString(m) }
func (*FeaturedItemsReply) ProtoMessage()    {}
func (*FeaturedItemsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_65d814d4061fbffb, []int{4}
}
func (m *FeaturedItemsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeaturedItemsReply.Unmarshal(m, b)
}
func (m *FeaturedItemsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeaturedItemsReply.Marshal(b, m, deterministic)
}
func (dst *FeaturedItemsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeaturedItemsReply.Merge(dst, src)
}
func (m *FeaturedItemsReply) XXX_Size() int {
	return xxx_messageInfo_FeaturedItemsReply.Size(m)
}
func (m *FeaturedItemsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FeaturedItemsReply.DiscardUnknown(m)
}

var xxx_messageInfo_FeaturedItemsReply proto.InternalMessageInfo

func (m *FeaturedItemsReply) GetItem() []*FeaturedItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "sparklepony.Empty")
	proto.RegisterType((*Item)(nil), "sparklepony.Item")
	proto.RegisterType((*FeaturedItem)(nil), "sparklepony.FeaturedItem")
	proto.RegisterType((*ItemsReply)(nil), "sparklepony.ItemsReply")
	proto.RegisterType((*FeaturedItemsReply)(nil), "sparklepony.FeaturedItemsReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	GetItems(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ItemsReply, error)
	GetFeatured(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FeaturedItemsReply, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) GetItems(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ItemsReply, error) {
	out := new(ItemsReply)
	err := c.cc.Invoke(ctx, "/sparklepony.Store/GetItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetFeatured(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FeaturedItemsReply, error) {
	out := new(FeaturedItemsReply)
	err := c.cc.Invoke(ctx, "/sparklepony.Store/GetFeatured", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	GetItems(context.Context, *Empty) (*ItemsReply, error)
	GetFeatured(context.Context, *Empty) (*FeaturedItemsReply, error)
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sparklepony.Store/GetItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetItems(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetFeatured_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetFeatured(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sparklepony.Store/GetFeatured",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetFeatured(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sparklepony.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItems",
			Handler:    _Store_GetItems_Handler,
		},
		{
			MethodName: "GetFeatured",
			Handler:    _Store_GetFeatured_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_65d814d4061fbffb) }

var fileDescriptor_service_65d814d4061fbffb = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0xb2, 0x4d, 0x9b, 0x4e, 0x61, 0xc5, 0x5a, 0x8b, 0xd6, 0x14, 0x16, 0x22, 0x4b, 0xa0,
	0x48, 0x88, 0x46, 0xec, 0x3e, 0x01, 0xe2, 0x67, 0xc5, 0x85, 0x43, 0x10, 0x5c, 0x57, 0xa6, 0x1d,
	0x2a, 0x43, 0x12, 0x1b, 0xc7, 0xad, 0xd4, 0x2b, 0xaf, 0xb0, 0x8f, 0xc5, 0x91, 0x37, 0x40, 0x3c,
	0x08, 0xca, 0x38, 0x5b, 0xb9, 0xa2, 0x20, 0x38, 0x7e, 0x33, 0xdf, 0x7c, 0xf3, 0xcd, 0x27, 0x1b,
	0x6e, 0xb6, 0x68, 0xd7, 0x6a, 0x8e, 0x33, 0x63, 0xb5, 0xd3, 0x6c, 0xd2, 0x1a, 0x69, 0x3f, 0x57,
	0x68, 0x74, 0xb3, 0x99, 0xde, 0x5b, 0x6a, 0xbd, 0xac, 0xb0, 0x90, 0x46, 0x15, 0xb2, 0x69, 0xb4,
	0x93, 0x4e, 0xe9, 0xa6, 0xf5, 0x54, 0x31, 0x82, 0xe4, 0x65, 0x6d, 0xdc, 0x46, 0x5c, 0xc5, 0x30,
	0x78, 0xed, 0xb0, 0x66, 0x87, 0x10, 0xab, 0x05, 0x8f, 0xb2, 0x28, 0x4f, 0xca, 0x58, 0x2d, 0xd8,
	0x31, 0x24, 0x4e, 0xb9, 0x0a, 0x79, 0x9c, 0x45, 0xf9, 0xb8, 0xf4, 0x80, 0x65, 0x30, 0x59, 0x60,
	0x3b, 0xb7, 0xca, 0x74, 0x6a, 0xfc, 0x80, 0x7a, 0x61, 0x89, 0xdd, 0x85, 0xb1, 0xaa, 0xe5, 0x12,
	0x2f, 0x57, 0xb6, 0xe2, 0x03, 0xea, 0xa7, 0x54, 0x78, 0x67, 0xab, 0x4e, 0xd4, 0x58, 0x35, 0x47,
	0x9e, 0x78, 0x51, 0x02, 0xec, 0x14, 0xa0, 0x75, 0xda, 0xe2, 0x65, 0x23, 0x6b, 0xe4, 0x43, 0x6a,
	0x8d, 0xa9, 0xf2, 0x46, 0xd6, 0xc8, 0x72, 0xb8, 0xe5, 0xdb, 0x72, 0x2d, 0x9d, 0xb4, 0x24, 0x3c,
	0x22, 0xd2, 0x21, 0xd5, 0x9f, 0x51, 0xb9, 0x93, 0x7f, 0x0c, 0x47, 0x9e, 0x19, 0x7a, 0x4c, 0x89,
	0xea, 0x25, 0x5e, 0x04, 0x46, 0xa7, 0x90, 0x7e, 0x44, 0xe9, 0x56, 0x16, 0x17, 0x7c, 0x9c, 0x45,
	0x79, 0x5a, 0x6e, 0xb1, 0xf8, 0x11, 0xc1, 0x8d, 0x57, 0x3d, 0xf8, 0x8f, 0x74, 0x8e, 0x21, 0xf9,
	0xb2, 0xd2, 0x0e, 0xfb, 0x5c, 0x3c, 0xf8, 0x7b, 0x22, 0xbb, 0xb7, 0x27, 0xff, 0x72, 0xfb, 0x70,
	0xef, 0xed, 0xdb, 0x68, 0x47, 0x61, 0xb4, 0x53, 0x48, 0xe7, 0xd2, 0xe1, 0x52, 0xdb, 0x4d, 0x1f,
	0xc4, 0x16, 0x8b, 0x73, 0x80, 0xee, 0xb6, 0xb6, 0x44, 0x53, 0x6d, 0xd8, 0x43, 0x18, 0x28, 0x87,
	0x35, 0x8f, 0xb2, 0x83, 0x7c, 0x72, 0x76, 0x34, 0x0b, 0xde, 0xd2, 0xac, 0xa3, 0x95, 0xd4, 0x16,
	0xcf, 0x81, 0x85, 0xc1, 0xf4, 0xc3, 0x4f, 0x76, 0x86, 0xef, 0xec, 0x0c, 0x87, 0x74, 0x2f, 0x72,
	0xf6, 0x2d, 0x82, 0xe4, 0x6d, 0x67, 0x9f, 0xbd, 0x87, 0xf4, 0x02, 0x1d, 0x29, 0x31, 0xb6, 0x33,
	0x46, 0xcf, 0x73, 0x7a, 0xf2, 0x9b, 0x0f, 0xbf, 0x51, 0x9c, 0x7e, 0xfd, 0xfe, 0xf3, 0x2a, 0x3e,
	0x11, 0xb7, 0x8b, 0x80, 0x50, 0xac, 0x9f, 0x16, 0x8a, 0xb4, 0x3e, 0xc1, 0xe4, 0x02, 0xdd, 0xf5,
	0xea, 0xbd, 0xd2, 0x0f, 0xfe, 0xe8, 0xb2, 0x5f, 0xf1, 0x88, 0x56, 0x64, 0xe2, 0xfe, 0xde, 0x15,
	0xc5, 0xf5, 0x63, 0xf9, 0x30, 0xa4, 0x2f, 0x75, 0xfe, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x6d,
	0xe1, 0xde, 0x8e, 0x03, 0x00, 0x00,
}
